name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          npm i
          npm un react-native-gesture-handler
          npm i react-native-gesture-handler@2.2.1
          npm cache clean --force
          npm ci
          CI=false npm run build
      - run: |
          git add ./src/metadata.json
          git commit -m "Update build number"
          git push
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./build/
          host: ${{ secrets.HOST }}
          remote: /home/siriusadmin/scp/
          username: ${{ secrets.USR }}
          privateKey: ${{ secrets.KEY }}
          rmRemote: true
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USR }}
          key: ${{ secrets.KEY }}
          script: /home/siriusadmin/deploy.sh


