name: Lint
on: [push]
jobs:
  StandardJS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.2.0
      - run: npm install standard
      - run: npx standard
