name: ssh test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y sshpass
      - run: |
          sshpass -p '${{ secrets.PWD }}' ssh -o StrictHostKeyChecking=no siriusadmin@137.184.68.35
          ls /home/
    


