on: [push, pull_request]
name: Standard
jobs:
  standardjs:
    name: StandardJs
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
    
    - name: standardjs-ga
      uses: devjoca/standardjs-action@0.4.0

