name: ssh test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i
          npm un react-native-gesture-handler
          npm i react-native-gesture-handler@2.2.1
          npm cache clean --force
          npm ci
          npm run build
          ls
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USR }}
          key: ${{ secrets.KEY }}
          script: |
            echo "hello"
    


